// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanMoHinh.API.Models;

#nullable disable

namespace WebBanMoHinh.API.Migrations
{
    [DbContext(typeof(WebBanMoHinhContext))]
    [Migration("20260611055258_AddVersionToSanPham")]
    partial class AddVersionToSanPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanMoHinh.API.Models.BinhLuanDanhGia", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime?>("NgayBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaBinhLuan")
                        .HasName("PK__BinhLuan__87CB66A0BE5B805F");

                    b.HasIndex("MaSp");

                    b.HasIndex("TenDangNhap");

                    b.ToTable("BinhLuanDanhGia");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietD__CDF0A1143BEBBEC8");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiDonHang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xác nhận");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHang__129584ADCC7F0EE2");

                    b.HasIndex("TenDangNhap");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.DongSanPham", b =>
                {
                    b.Property<int>("MaDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDong"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDong")
                        .HasName("PK__DongSanP__2DC5878944E16099");

                    b.ToTable("DongSanPham");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.GioHang", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CartJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<string>("UrlAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaAnh")
                        .HasName("PK__HinhAnhS__356240DF9C92BAE7");

                    b.HasIndex("MaSp");

                    b.ToTable("HinhAnhSanPham");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.LichSuDauGia", b =>
                {
                    b.Property<int>("MaLuotBidding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuotBidding"));

                    b.Property<int>("MaPhien")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienDau")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ThoiGianDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaLuotBidding")
                        .HasName("PK__LichSuDa__DC59C3250C9DC9C9");

                    b.HasIndex("MaPhien");

                    b.HasIndex("TenDangNhap");

                    b.ToTable("LichSuDauGia");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiSanP__730A5759F0AC8C39");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.NhaSanXuat", b =>
                {
                    b.Property<int>("MaNsx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNSX");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNsx"));

                    b.Property<string>("QuocGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNsx")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenNSX");

                    b.HasKey("MaNsx")
                        .HasName("PK__NhaSanXu__3A1BDBD23F33979E");

                    b.ToTable("NhaSanXuat");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.PhienDauGia", b =>
                {
                    b.Property<int>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhien"));

                    b.Property<decimal>("BuocGiaMin")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaHienTai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaKhoiDiem")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaMuaNgay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("SapDienRa");

                    b.Property<byte[]>("VersRow")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("MaPhien")
                        .HasName("PK__PhienDau__2660BFEF9EA830D6");

                    b.HasIndex("MaSp");

                    b.ToTable("PhienDauGia");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<string>("ChatLieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("HinhAnhChinh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsHot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LoaiHinhHienThi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("BanThang");

                    b.Property<int?>("MaDong")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int?>("MaNsx")
                        .HasColumnType("int")
                        .HasColumnName("MaNSX");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TenSP");

                    b.Property<string>("TiLe")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C6E032B48");

                    b.HasIndex("MaDong");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNsx");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer");

                    b.HasKey("TenDangNhap")
                        .HasName("PK__TaiKhoan__55F68FC181E43542");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.BinhLuanDanhGia", b =>
                {
                    b.HasOne("WebBanMoHinh.API.Models.SanPham", "MaSpNavigation")
                        .WithMany("BinhLuanDanhGia")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK_BL_SP");

                    b.HasOne("WebBanMoHinh.API.Models.TaiKhoan", "TenDangNhapNavigation")
                        .WithMany("BinhLuanDanhGia")
                        .HasForeignKey("TenDangNhap")
                        .HasConstraintName("FK_BL_TK");

                    b.Navigation("MaSpNavigation");

                    b.Navigation("TenDangNhapNavigation");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("WebBanMoHinh.API.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("FK_CTDH_DonHang");

                    b.HasOne("WebBanMoHinh.API.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK_CTDH_SP");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.DonHang", b =>
                {
                    b.HasOne("WebBanMoHinh.API.Models.TaiKhoan", "TenDangNhapNavigation")
                        .WithMany("DonHang")
                        .HasForeignKey("TenDangNhap")
                        .HasConstraintName("FK_DonHang_TK");

                    b.Navigation("TenDangNhapNavigation");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.GioHang", b =>
                {
                    b.HasOne("WebBanMoHinh.API.Models.TaiKhoan", "TenDangNhapNavigation")
                        .WithOne()
                        .HasForeignKey("WebBanMoHinh.API.Models.GioHang", "TenDangNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GioHang_TaiKhoan");

                    b.Navigation("TenDangNhapNavigation");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.HinhAnhSanPham", b =>
                {
                    b.HasOne("WebBanMoHinh.API.Models.SanPham", "MaSpNavigation")
                        .WithMany("HinhAnhSanPham")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK_Anh_SP");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.LichSuDauGia", b =>
                {
                    b.HasOne("WebBanMoHinh.API.Models.PhienDauGia", "MaPhienNavigation")
                        .WithMany("LichSuDauGia")
                        .HasForeignKey("MaPhien")
                        .IsRequired()
                        .HasConstraintName("FK_LSDG_Phien");

                    b.HasOne("WebBanMoHinh.API.Models.TaiKhoan", "TenDangNhapNavigation")
                        .WithMany("LichSuDauGia")
                        .HasForeignKey("TenDangNhap")
                        .IsRequired()
                        .HasConstraintName("FK_LSDG_TaiKhoan");

                    b.Navigation("MaPhienNavigation");

                    b.Navigation("TenDangNhapNavigation");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.PhienDauGia", b =>
                {
                    b.HasOne("WebBanMoHinh.API.Models.SanPham", "MaSpNavigation")
                        .WithMany("PhienDauGia")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_PDG_SanPham");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.SanPham", b =>
                {
                    b.HasOne("WebBanMoHinh.API.Models.DongSanPham", "MaDongNavigation")
                        .WithMany("SanPham")
                        .HasForeignKey("MaDong")
                        .HasConstraintName("FK_SP_DongSanPham");

                    b.HasOne("WebBanMoHinh.API.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPham")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK_SP_Loai");

                    b.HasOne("WebBanMoHinh.API.Models.NhaSanXuat", "MaNsxNavigation")
                        .WithMany("SanPham")
                        .HasForeignKey("MaNsx")
                        .HasConstraintName("FK_SP_NSX");

                    b.Navigation("MaDongNavigation");

                    b.Navigation("MaLoaiNavigation");

                    b.Navigation("MaNsxNavigation");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.DongSanPham", b =>
                {
                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.NhaSanXuat", b =>
                {
                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.PhienDauGia", b =>
                {
                    b.Navigation("LichSuDauGia");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.SanPham", b =>
                {
                    b.Navigation("BinhLuanDanhGia");

                    b.Navigation("ChiTietDonHang");

                    b.Navigation("HinhAnhSanPham");

                    b.Navigation("PhienDauGia");
                });

            modelBuilder.Entity("WebBanMoHinh.API.Models.TaiKhoan", b =>
                {
                    b.Navigation("BinhLuanDanhGia");

                    b.Navigation("DonHang");

                    b.Navigation("LichSuDauGia");
                });
#pragma warning restore 612, 618
        }
    }
}
